[package]
name = "notes_vercel_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.19.2"
chrono = { version = "0.4.45", features = ["serde"] }
dotenvy = "0.15.7"
http = "1"
http-body-util = "0.1"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
native-tls = { version = "0.2", features = ["vendored"] }
postgres = { version = "0.19", features = ["with-chrono-0_4", "with-uuid-1"] }
postgres-native-tls = "0.5"
r2d2 = "0.8"
r2d2_postgres = "0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4", "serde"] }
vercel_runtime = "=2.3.0"

[[bin]]
name = "index"
path = "api/index.rs"

